# Generated by Django 4.2.11 on 2025-04-28 14:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID задачи')),
                ('title', models.CharField(help_text='Название задачи', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Описание задачи')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('block', 'Блокер')], default='medium', help_text='Приоритет задачи', max_length=10)),
                ('deadline_start', models.DateTimeField(blank=True, help_text='Начало срока выполнения', null=True)),
                ('deadline_end', models.DateTimeField(blank=True, help_text='Конец срока выполнения', null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['task_id'],
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID статуса')),
                ('name', models.CharField(help_text='Название статуса', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Порядок отображения статуса')),
                ('color', models.CharField(default='#A0A9F3', help_text='Цвет статуса в формате HEX', max_length=7)),
                ('user_id', models.ForeignKey(help_text='Владелец статуса', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID категории')),
                ('name', models.CharField(help_text='Название категории', max_length=100)),
                ('user_id', models.ForeignKey(help_text='Владелец категории', on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Категория задачи',
                'verbose_name_plural': 'Категории задач',
                'ordering': ['name'],
                'unique_together': {('name', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID вложения')),
                ('name', models.CharField(help_text='Название файла', max_length=255)),
                ('path', models.FileField(help_text='Путь к файлу', upload_to='task_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'])])),
                ('size', models.IntegerField(help_text='Размер файла в байтах')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Дата загрузки')),
                ('task_id', models.ForeignKey(help_text='Задача', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('user_id', models.ForeignKey(help_text='Владелец файла', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='category_id',
            field=models.ForeignKey(blank=True, help_text='Категория задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='note_id',
            field=models.ForeignKey(blank=True, help_text='Заметка задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='notes.note'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_id',
            field=models.ForeignKey(help_text='Статус задачи', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(help_text='Владелец задачи', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
