# Generated by Django 4.2.11 on 2025-04-17 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='user_id',
            field=models.ForeignKey(help_text='Владелец статуса', on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='user_id',
            field=models.ForeignKey(help_text='Владелец категории', on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='category_id',
            field=models.ForeignKey(blank=True, help_text='Категория задачи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_id',
            field=models.ForeignKey(help_text='Статус задачи', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.taskstatus'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(help_text='Владелец задачи', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='taskstatus',
            unique_together={('name', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='taskcategory',
            unique_together={('name', 'user_id')},
        ),
    ]
