# Generated by Django 4.2.11 on 2025-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_taskattachment_task_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задач'},
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='color',
            field=models.CharField(default='#A0A9F3', help_text='Цвет статуса в формате HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения статуса'),
        ),
    ]
