# Generated by Django 4.2.11 on 2025-04-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskstatus_options_taskstatus_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('block', 'Блокер')], default='medium', help_text='Приоритет задачи', max_length=10),
        ),
    ]
