# Generated by Django 4.2.11 on 2025-04-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_end',
            field=models.DateTimeField(blank=True, help_text='Конец срока выполнения', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='deadline_start',
            field=models.DateTimeField(blank=True, help_text='Начало срока выполнения', null=True),
        ),
    ]
