# Generated by Django 4.2.11 on 2025-04-17 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='user_id',
            field=models.ManyToManyField(help_text='Владельцы ссылки', related_name='links', to=settings.AUTH_USER_MODEL),
        ),
    ]
