# Generated by Django 4.2.11 on 2025-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Аватар пользователя', null=True, upload_to='avatars/', verbose_name='аватар'),
        ),
    ]
