# Generated by Django 4.2.11 on 2025-04-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название файла', max_length=255)),
                ('file', models.FileField(help_text='Файл', upload_to='files/%Y/%m/%d/')),
                ('size', models.BigIntegerField(help_text='Размер файла в байтах')),
                ('is_favorite', models.BooleanField(default=False, help_text='Пометка избранного')),
                ('is_trashed', models.BooleanField(default=False, help_text='Пометка удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название папки', max_length=255)),
                ('is_favorite', models.BooleanField(default=False, help_text='Пометка избранного')),
                ('is_trashed', models.BooleanField(default=False, help_text='Пометка удаления')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата обновления')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская папка', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files.folder')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'ordering': ['-updated_at'],
            },
        ),
    ]
