# Generated by Django 4.2.11 on 2025-05-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='folder_id',
            field=models.ForeignKey(blank=True, help_text='Папка файла', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.folder'),
        ),
    ]
